version: '3.8'

services:
  db:
    container_name: facturino_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=facturino
      - POSTGRES_DB=facturino
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U facturino"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: facturino_app
    image: php:8.2-fpm
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - PHP_MEMORY_LIMIT=512M
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        apt-get update && apt-get install -y libpq-dev zip unzip git &&
        docker-php-ext-install pdo pdo_pgsql &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        composer install --no-interaction --no-dev --optimize-autoloader &&
        php artisan key:generate --force &&
        php artisan migrate --force &&
        php artisan db:seed --force &&
        php artisan optimize:clear &&
        php-fpm
      "

  nginx:
    container_name: facturino_nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app