<?php

namespace App\Services\WooCommerce;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

/**
 * WooCommerce REST API client.
 *
 * Wraps the WooCommerce REST API for fetching orders, products, and customers.
 * Requires consumer key + consumer secret generated by the store owner.
 *
 * @see https://woocommerce.github.io/woocommerce-rest-api-docs/
 */
class WooCommerceClient
{
    protected string $storeUrl;

    protected string $consumerKey;

    protected string $consumerSecret;

    protected string $apiVersion;

    public function __construct(string $storeUrl, string $consumerKey, string $consumerSecret)
    {
        $this->storeUrl = rtrim($storeUrl, '/');
        $this->consumerKey = $consumerKey;
        $this->consumerSecret = $consumerSecret;
        $this->apiVersion = 'wc/v3';
    }

    /**
     * Create a client from config values for a given company.
     */
    public static function fromConfig(array $config): self
    {
        return new self(
            $config['store_url'] ?? '',
            $config['consumer_key'] ?? '',
            $config['consumer_secret'] ?? ''
        );
    }

    /**
     * Test the connection to the WooCommerce store.
     *
     * @return array{success: bool, store_name: string|null, error: string|null}
     */
    public function testConnection(): array
    {
        try {
            $response = $this->get('');

            if (isset($response['store'])) {
                return [
                    'success' => true,
                    'store_name' => $response['store']['name'] ?? $response['description'] ?? null,
                    'error' => null,
                ];
            }

            return ['success' => true, 'store_name' => $response['name'] ?? null, 'error' => null];
        } catch (\Throwable $e) {
            return ['success' => false, 'store_name' => null, 'error' => $e->getMessage()];
        }
    }

    /**
     * Fetch orders from WooCommerce.
     *
     * @param  array  $params  Query parameters (status, after, before, page, per_page)
     * @return array
     */
    public function getOrders(array $params = []): array
    {
        $defaults = [
            'status' => 'processing,completed',
            'per_page' => 50,
            'page' => 1,
            'orderby' => 'date',
            'order' => 'desc',
        ];

        return $this->get('orders', array_merge($defaults, $params));
    }

    /**
     * Fetch a single order by ID.
     *
     * @param  int  $orderId  WooCommerce order ID
     * @return array
     */
    public function getOrder(int $orderId): array
    {
        return $this->get("orders/{$orderId}");
    }

    /**
     * Update order status or add a note.
     *
     * @param  int  $orderId  WooCommerce order ID
     * @param  array  $data  Fields to update
     * @return array
     */
    public function updateOrder(int $orderId, array $data): array
    {
        return $this->put("orders/{$orderId}", $data);
    }

    /**
     * Fetch tax classes.
     *
     * @return array
     */
    public function getTaxClasses(): array
    {
        return $this->get('taxes/classes');
    }

    /**
     * Make a GET request to the WooCommerce API.
     */
    protected function get(string $endpoint, array $params = []): array
    {
        $url = "{$this->storeUrl}/wp-json/{$this->apiVersion}/{$endpoint}";

        $response = Http::timeout(30)
            ->connectTimeout(10)
            ->withBasicAuth($this->consumerKey, $this->consumerSecret)
            ->get($url, $params);

        if (! $response->successful()) {
            $error = $response->json('message') ?? "HTTP {$response->status()}";

            throw new \RuntimeException("WooCommerce API error: {$error}");
        }

        return $response->json() ?? [];
    }

    /**
     * Make a PUT request to the WooCommerce API.
     */
    protected function put(string $endpoint, array $data): array
    {
        $url = "{$this->storeUrl}/wp-json/{$this->apiVersion}/{$endpoint}";

        $response = Http::timeout(30)
            ->connectTimeout(10)
            ->withBasicAuth($this->consumerKey, $this->consumerSecret)
            ->put($url, $data);

        if (! $response->successful()) {
            $error = $response->json('message') ?? "HTTP {$response->status()}";

            throw new \RuntimeException("WooCommerce API error: {$error}");
        }

        return $response->json() ?? [];
    }
}
// CLAUDE-CHECKPOINT
