<?php

use App\Models\Bill;
use App\Models\Customer;
use App\Models\CustomField;
use App\Models\Estimate;
use App\Models\Expense;
use App\Models\Invoice;
use App\Models\Item;
use App\Models\Note;
use App\Models\Payment;
use App\Models\ProformaInvoice;
use App\Models\Project;
use App\Models\RecurringInvoice;
use App\Models\Supplier;
use App\Models\TaxType;

return [

    /*
    * Minimum php version.
    */
    'min_php_version' => '8.2.0',

    /*
    * Minimum mysql version.
    */

    'min_mysql_version' => '5.7.7',

    /*
    * Minimum mariadb version.
    */

    'min_mariadb_version' => '10.2.7',

    /*
    * Minimum pgsql version.
    */

    'min_pgsql_version' => '9.2.0',

    /*
    * Minimum sqlite version.
    */

    'min_sqlite_version' => '3.35.0',

    /*
    * Marketplace url.
    */
    'base_url' => 'https://invoiceshelf.com',

    /*
    * List of languages supported by Facturino.
    */
    'languages' => [
        ['code' => 'mk', 'name' => 'Macedonian'],
        ['code' => 'en', 'name' => 'English'],
        ['code' => 'sq', 'name' => 'Albanian'],
        ['code' => 'tr', 'name' => 'Turkish'],
    ],

    /*
    * List of Fiscal Years
    */
    'fiscal_years' => [
        ['key' => 'settings.preferences.fiscal_years.january_december', 'value' => '1-12'],
        ['key' => 'settings.preferences.fiscal_years.february_january', 'value' => '2-1'],
        ['key' => 'settings.preferences.fiscal_years.march_february', 'value' => '3-2'],
        ['key' => 'settings.preferences.fiscal_years.april_march', 'value' => '4-3'],
        ['key' => 'settings.preferences.fiscal_years.may_april', 'value' => '5-4'],
        ['key' => 'settings.preferences.fiscal_years.june_may', 'value' => '6-5'],
        ['key' => 'settings.preferences.fiscal_years.july_june', 'value' => '7-6'],
        ['key' => 'settings.preferences.fiscal_years.august_july', 'value' => '8-7'],
        ['key' => 'settings.preferences.fiscal_years.september_august', 'value' => '9-8'],
        ['key' => 'settings.preferences.fiscal_years.october_september', 'value' => '10-9'],
        ['key' => 'settings.preferences.fiscal_years.november_october', 'value' => '11-10'],
        ['key' => 'settings.preferences.fiscal_years.december_november', 'value' => '12-11'],
    ],

    /*
    * List of convert estimate options
    */
    'convert_estimate_options' => [
        ['key' => 'settings.preferences.no_action', 'value' => 'no_action'],
        ['key' => 'settings.preferences.delete_estimate', 'value' => 'delete_estimate'],
        ['key' => 'settings.preferences.mark_estimate_as_accepted', 'value' => 'mark_estimate_as_accepted'],
    ],

    /*
    * List of retrospective edits
    */
    'retrospective_edits' => [
        ['key' => 'settings.preferences.allow', 'value' => 'allow'],
        ['key' => 'settings.preferences.disable_on_invoice_partial_paid', 'value' => 'disable_on_invoice_partial_paid'],
        ['key' => 'settings.preferences.disable_on_invoice_paid', 'value' => 'disable_on_invoice_paid'],
        ['key' => 'settings.preferences.disable_on_invoice_sent', 'value' => 'disable_on_invoice_sent'],
    ],

    /*
    * List of setting menu
    */
    'setting_menu' => [
        [
            'title' => 'settings.menu_title.account_settings',
            'group' => '',
            'name' => 'Account Settings',
            'link' => '/admin/settings/account-settings',
            'icon' => 'UserIcon',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.menu_title.privacy_data',
            'group' => '',
            'name' => 'Privacy & Data',
            'link' => '/admin/settings/privacy-data',
            'icon' => 'ShieldCheckIcon',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.menu_title.company_information',
            'group' => '',
            'name' => 'Company information',
            'link' => '/admin/settings/company-info',
            'icon' => 'BuildingOfficeIcon',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.menu_title.preferences',
            'group' => '',
            'name' => 'Preferences',
            'link' => '/admin/settings/preferences',
            'icon' => 'CogIcon',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.menu_title.customization',
            'group' => '',
            'name' => 'Customization',
            'link' => '/admin/settings/customization',
            'icon' => 'PencilSquareIcon',
            'owner_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.menu_title.pdf_generation',
            'group' => '',
            'name' => 'PDF Generation',
            'link' => '/admin/settings/pdf-generation',
            'icon' => 'DocumentIcon',
            'owner_only' => true,
            'super_admin_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.roles.title',
            'group' => '',
            'name' => 'Roles',
            'link' => '/admin/settings/roles-settings',
            'icon' => 'UserGroupIcon',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.menu_title.partner_settings',
            'group' => '',
            'name' => 'Partner Management',
            'link' => '/admin/settings/partner-settings',
            'icon' => 'UsersIcon',
            'owner_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.menu_title.invite_company',
            'group' => '',
            'name' => 'Invite Company',
            'link' => '/admin/settings/invite-company',
            'icon' => 'LinkIcon',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        // Exchange Rate Provider removed - using free Frankfurter API (no config needed)
        [
            'title' => 'settings.menu_title.notifications',
            'group' => '',
            'name' => 'Notifications',
            'link' => '/admin/settings/notifications',
            'icon' => 'BellIcon',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.menu_title.tax_types',
            'group' => '',
            'name' => 'Tax types',
            'link' => '/admin/settings/tax-types',
            'icon' => 'CheckCircleIcon',
            'owner_only' => false,
            'ability' => 'view-tax-type',
            'model' => TaxType::class,
        ],
        [
            'title' => 'settings.menu_title.payment_modes',
            'group' => '',
            'name' => 'Payment modes',
            'link' => '/admin/settings/payment-mode',
            'icon' => 'CreditCardIcon',
            'owner_only' => false,
            'ability' => 'view-payment',
            'model' => Payment::class,
        ],
        [
            'title' => 'settings.menu_title.custom_fields',
            'group' => '',
            'name' => 'Custom fields',
            'link' => '/admin/settings/custom-fields',
            'icon' => 'CubeIcon',
            'owner_only' => false,
            'ability' => 'view-custom-field',
            'model' => CustomField::class,
        ],
        [
            'title' => 'settings.menu_title.notes',
            'group' => '',
            'name' => 'Notes',
            'link' => '/admin/settings/notes',
            'icon' => 'ClipboardDocumentCheckIcon',
            'owner_only' => false,
            'ability' => 'view-all-notes',
            'model' => Note::class,
        ],
        [
            'title' => 'settings.menu_title.expense_category',
            'group' => '',
            'name' => 'Expense Category',
            'link' => '/admin/settings/expense-category',
            'icon' => 'ClipboardDocumentListIcon',
            'owner_only' => false,
            'ability' => 'view-expense',
            'model' => Expense::class,
        ],
        // Mail Configuration removed - using centralized Postmark setup
        [
            'title' => 'settings.menu_title.file_disk',
            'group' => '',
            'name' => 'File Disk',
            'link' => '/admin/settings/file-disk',
            'icon' => 'FolderIcon',
            'owner_only' => true,
            'super_admin_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.menu_title.backup',
            'group' => '',
            'name' => 'Backup',
            'link' => '/admin/settings/backup',
            'icon' => 'CircleStackIcon',
            'owner_only' => true,
            'super_admin_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.feature_flags.title',
            'group' => '',
            'name' => 'Feature Flags',
            'link' => '/admin/settings/feature-flags',
            'icon' => 'FlagIcon',
            'owner_only' => true,
            'super_admin_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'settings.menu_title.fiscal_devices',
            'group' => '',
            'name' => 'Fiscal Devices',
            'link' => '/admin/settings/fiscal-devices',
            'icon' => 'PrinterIcon',
            'owner_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'pos_settings.title',
            'group' => '',
            'name' => 'POS Settings',
            'link' => '/admin/settings/pos',
            'icon' => 'ShoppingCartIcon',
            'owner_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'Viber Notifications',
            'group' => '',
            'name' => 'Viber Notifications',
            'link' => '/admin/settings/viber-notifications',
            'icon' => 'ChatBubbleLeftRightIcon',
            'owner_only' => true,
            'super_admin_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'WooCommerce',
            'group' => '',
            'name' => 'WooCommerce',
            'link' => '/admin/settings/woocommerce',
            'icon' => 'ShoppingCartIcon',
            'owner_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'E-Faktura',
            'group' => '',
            'name' => 'E-Faktura',
            'link' => '/admin/settings/efaktura',
            'icon' => 'DocumentTextIcon',
            'owner_only' => true,
            'ability' => '',
            'model' => '',
        ],
        // NOTE: Chart of Accounts, Period Lock, Daily Closing, and Journal Export
        // have been moved to Partner Accounting section (partner-only features)
    ],

    /*
    * List of main menu
    */
    'main_menu' => [
        [
            'title' => 'navigation.dashboard',
            'group' => 1,
            'link' => '/admin/dashboard',
            'icon' => 'HomeIcon',
            'name' => 'Dashboard',
            'owner_only' => false,
            'ability' => 'dashboard',
            'model' => '',
        ],
        [
            'title' => 'navigation.customers',
            'group' => 1,
            'link' => '/admin/customers',
            'icon' => 'UserIcon',
            'name' => 'Customers',
            'owner_only' => false,
            'ability' => 'view-customer',
            'model' => Customer::class,
        ],
        [
            'title' => 'navigation.items',
            'group' => 1,
            'link' => '/admin/items',
            'icon' => 'StarIcon',
            'name' => 'Items',
            'owner_only' => false,
            'ability' => 'view-item',
            'model' => Item::class,
        ],
        [
            'title' => 'navigation.estimates',
            'group' => 2,
            'link' => '/admin/estimates',
            'icon' => 'DocumentIcon',
            'name' => 'Estimates',
            'owner_only' => false,
            'ability' => 'view-estimate',
            'model' => Estimate::class,
        ],
        [
            'title' => 'navigation.proforma_invoices',
            'group' => 2,
            'link' => '/admin/proforma-invoices',
            'icon' => 'DocumentDuplicateIcon',
            'name' => 'Proforma Invoices',
            'owner_only' => false,
            'ability' => 'view-estimate',
            'model' => ProformaInvoice::class,
        ],
        [
            'title' => 'navigation.invoices',
            'group' => 2,
            'link' => '/admin/invoices',
            'icon' => 'DocumentTextIcon',
            'name' => 'Invoices',
            'owner_only' => false,
            'ability' => 'view-invoice',
            'model' => Invoice::class,
        ],
        [
            'title' => 'navigation.recurring-invoices',
            'group' => 2,
            'link' => '/admin/recurring-invoices',
            'icon' => 'DocumentTextIcon',
            'name' => 'Recurring Invoices',
            'owner_only' => false,
            'ability' => 'view-recurring-invoice',
            'model' => RecurringInvoice::class,
        ],
        [
            'title' => 'navigation.payments',
            'group' => 2,
            'link' => '/admin/payments',
            'icon' => 'CreditCardIcon',
            'name' => 'Payments',
            'owner_only' => false,
            'ability' => 'view-payment',
            'model' => Payment::class,
        ],
        [
            'title' => 'navigation.expenses',
            'group' => 2,
            'link' => '/admin/expenses',
            'icon' => 'CalculatorIcon',
            'name' => 'Expenses',
            'owner_only' => false,
            'ability' => 'view-expense',
            'model' => Expense::class,
        ],
        [
            'title' => 'navigation.suppliers',
            'group' => 2,
            'link' => '/admin/suppliers',
            'icon' => 'BuildingStorefrontIcon',
            'name' => 'Suppliers',
            'owner_only' => false,
            'ability' => 'view-supplier',
            'model' => Supplier::class,
        ],
        [
            'title' => 'navigation.bills',
            'group' => 2,
            'link' => '/admin/bills',
            'icon' => 'ClipboardDocumentListIcon',
            'name' => 'Bills',
            'owner_only' => false,
            'ability' => 'view-bill',
            'model' => Bill::class,
        ],
        [
            'title' => 'navigation.documents',
            'group' => 2,
            'link' => '/admin/documents',
            'icon' => 'DocumentArrowUpIcon',
            'name' => 'Documents',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        // ── Operations (collapsible submenu) ──
        [
            'title' => 'navigation.pos',
            'group' => 2,
            'submenu' => 'operations',
            'link' => '/admin/pos',
            'icon' => 'ShoppingCartIcon',
            'name' => 'POS',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.compensations',
            'group' => 2,
            'submenu' => 'operations',
            'link' => '/admin/compensations',
            'icon' => 'ArrowsRightLeftIcon',
            'name' => 'Compensations',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.purchase_orders',
            'group' => 2,
            'submenu' => 'operations',
            'link' => '/admin/purchase-orders',
            'icon' => 'ShoppingCartIcon',
            'name' => 'Purchase Orders',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.payment_orders',
            'group' => 2,
            'submenu' => 'operations',
            'link' => '/admin/payment-orders',
            'icon' => 'BanknotesIcon',
            'name' => 'Payment Orders',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.travel_orders',
            'group' => 2,
            'submenu' => 'operations',
            'link' => '/admin/travel-orders',
            'icon' => 'TruckIcon',
            'name' => 'Travel Orders',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.cost_centers',
            'group' => 2,
            'submenu' => 'operations',
            'link' => '/admin/cost-centers',
            'icon' => 'BuildingOffice2Icon',
            'name' => 'Cost Centers',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.stock',
            'group' => 2,
            'submenu' => 'operations',
            'link' => '/admin/stock',
            'icon' => 'ArchiveBoxIcon',
            'name' => 'Stock',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.manufacturing',
            'group' => 2,
            'submenu' => 'operations',
            'link' => '/admin/manufacturing',
            'icon' => 'CogIcon',
            'name' => 'Manufacturing',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.fiscal_receipts',
            'group' => 2,
            'submenu' => 'operations',
            'link' => '/admin/fiscal-receipts',
            'icon' => 'ReceiptPercentIcon',
            'name' => 'Fiscal Receipts',
            'owner_only' => false,
            'ability' => 'view-fiscal-monitor',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.fiscal_monitor',
            'group' => 2,
            'submenu' => 'operations',
            'link' => '/admin/fiscal-monitor',
            'icon' => 'ShieldExclamationIcon',
            'name' => 'Fiscal Monitor',
            'owner_only' => false,
            'ability' => 'view-fiscal-monitor',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.projects',
            'group' => 2,
            'submenu' => 'operations',
            'link' => '/admin/projects',
            'icon' => 'FolderIcon',
            'name' => 'Projects',
            'owner_only' => false,
            'ability' => 'view-project',
            'model' => Project::class,
            'feature_flag' => 'accounting_backbone',
        ],
        // CLAUDE-CHECKPOINT
        [
            'title' => 'navigation.banking',
            'group' => 2,
            'link' => '/admin/banking',
            'icon' => 'BanknotesIcon',
            'name' => 'Banking',
            'owner_only' => false,
            'ability' => 'view-report',
            'model' => '',
            'feature_flag' => 'psd2_banking',
        ],
        [
            'title' => 'navigation.payroll',
            'group' => 2,
            'link' => '/admin/payroll',
            'icon' => 'BriefcaseIcon',
            'name' => 'Payroll',
            'owner_only' => false,
            'ability' => 'view-payroll-employee',
            'model' => \App\Models\PayrollEmployee::class,
            'feature_flag' => 'payroll',
        ],
        [
            'title' => 'navigation.deadlines',
            'group' => 2,
            'link' => '/admin/deadlines',
            'icon' => 'ClockIcon',
            'name' => 'Deadlines',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.billing',
            'group' => 3,
            'link' => '/admin/billing',
            'icon' => 'CreditCardIcon',
            'name' => 'Billing',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.users',
            'group' => 3,
            'link' => '/admin/users',
            'icon' => 'UsersIcon',
            'name' => 'Users',
            'owner_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.reports',
            'group' => 3,
            'link' => '/admin/reports',
            'icon' => 'ChartBarIcon',
            'name' => 'Reports',
            'owner_only' => false,
            'ability' => 'view-financial-reports',
            'model' => '',
        ],
        // ── Finance (collapsible submenu) ──
        [
            'title' => 'navigation.bi_dashboard',
            'group' => 3,
            'submenu' => 'finance',
            'link' => '/admin/bi-dashboard',
            'icon' => 'PresentationChartLineIcon',
            'name' => 'BI Dashboard',
            'owner_only' => false,
            'ability' => 'view-financial-reports',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.budgets',
            'group' => 3,
            'submenu' => 'finance',
            'link' => '/admin/budgets',
            'icon' => 'CalculatorIcon',
            'name' => 'Budgets',
            'owner_only' => false,
            'ability' => 'view-financial-reports',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        // Custom Reports — moved to partner-only (IFRS data not relevant for companies)
        [
            'title' => 'navigation.interest',
            'group' => 3,
            'submenu' => 'finance',
            'link' => '/admin/interest',
            'icon' => 'ReceiptPercentIcon',
            'name' => 'Interest Calculator',
            'owner_only' => false,
            'ability' => 'view-financial-reports',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.collections',
            'group' => 3,
            'submenu' => 'finance',
            'link' => '/admin/collections',
            'icon' => 'BellAlertIcon',
            'name' => 'Collections',
            'owner_only' => false,
            'ability' => 'view-financial-reports',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'navigation.setup_wizard',
            'group' => 3,
            'link' => '/admin/onboarding',
            'icon' => 'SparklesIcon',
            'name' => 'Setup Wizard',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.migration_wizard',
            'group' => 3,
            'link' => '/admin/imports',
            'icon' => 'ArrowDownTrayIcon',
            'name' => 'Migration Wizard',
            'owner_only' => false,
            'ability' => 'create-customer',
            'model' => Customer::class,
        ],
        [
            'title' => 'navigation.settings',
            'group' => 3,
            'link' => '/admin/settings',
            'icon' => 'CogIcon',
            'name' => 'Settings',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.support',
            'group' => 3,
            'link' => '/admin/support',
            'icon' => 'LifebuoyIcon',
            'name' => 'Support',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.all_support_tickets',
            'group' => 3,
            'link' => '/admin/support-admin',
            'icon' => 'TicketIcon',
            'name' => 'All Support Tickets',
            'owner_only' => false,
            'super_admin_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.payouts',
            'group' => 3,
            'link' => '/admin/payouts',
            'icon' => 'BanknotesIcon',
            'name' => 'Payouts',
            'owner_only' => false,
            'super_admin_only' => true,
            'ability' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.partners',
            'group' => 3,
            'link' => '/admin/partners',
            'icon' => 'UserGroupIcon',
            'name' => 'Partners',
            'owner_only' => false,
            'super_admin_only' => true,
            'ability' => '',
            'model' => '',
        ],
        // ── Setup (Подготовка) ──
        [
            'title' => 'partner.accounting.onboarding_wizard',
            'group' => 'partner.accounting',
            'submenu' => 'setup',
            'link' => '/admin/partner/onboarding',
            'icon' => 'SparklesIcon',
            'name' => 'partner.accounting.onboarding-wizard',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.chart_of_accounts',
            'group' => 'partner.accounting',
            'submenu' => 'setup',
            'link' => '/admin/partner/accounting/chart-of-accounts',
            'icon' => 'TableCellsIcon',
            'name' => 'partner.accounting.chart-of-accounts',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.journal_import.title',
            'group' => 'partner.accounting',
            'submenu' => 'setup',
            'link' => '/admin/partner/accounting/journal-import',
            'icon' => 'ArrowUpTrayIcon',
            'name' => 'partner.accounting.journal-import',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        // ── Ledgers (Книжења) ──
        [
            'title' => 'partner.accounting.journal_review',
            'group' => 'partner.accounting',
            'submenu' => 'ledgers',
            'link' => '/admin/partner/accounting/review',
            'icon' => 'MagnifyingGlassIcon',
            'name' => 'partner.accounting.review',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.journal_export',
            'group' => 'partner.accounting',
            'submenu' => 'ledgers',
            'link' => '/admin/partner/accounting/export',
            'icon' => 'ArrowDownTrayIcon',
            'name' => 'partner.accounting.export',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.journal_entries',
            'group' => 'partner.accounting',
            'submenu' => 'ledgers',
            'link' => '/admin/partner/accounting/journal-entries',
            'icon' => 'ClipboardDocumentListIcon',
            'name' => 'partner.accounting.journal-entries',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.general_ledger',
            'group' => 'partner.accounting',
            'submenu' => 'ledgers',
            'link' => '/admin/partner/accounting/general-ledger',
            'icon' => 'BookmarkIcon',
            'name' => 'partner.accounting.general-ledger',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.sub_ledger',
            'group' => 'partner.accounting',
            'submenu' => 'ledgers',
            'link' => '/admin/partner/accounting/sub-ledger',
            'icon' => 'BookmarkSquareIcon',
            'name' => 'partner.accounting.sub-ledger',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.cash_book',
            'group' => 'partner.accounting',
            'submenu' => 'ledgers',
            'link' => '/admin/partner/accounting/cash-book',
            'icon' => 'BanknotesIcon',
            'name' => 'partner.accounting.cash-book',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.daily_closing',
            'group' => 'partner.accounting',
            'submenu' => 'ledgers',
            'link' => '/admin/partner/accounting/daily-closing',
            'icon' => 'CalendarDaysIcon',
            'name' => 'partner.accounting.daily-closing',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        // ── Reports (Извештаи) ──
        [
            'title' => 'partner.accounting.trial_balance',
            'group' => 'partner.accounting',
            'submenu' => 'reports',
            'link' => '/admin/partner/accounting/trial-balance',
            'icon' => 'ScaleIcon',
            'name' => 'partner.accounting.trial-balance',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.cash_flow',
            'group' => 'partner.accounting',
            'submenu' => 'reports',
            'link' => '/admin/partner/accounting/cash-flow',
            'icon' => 'ArrowsRightLeftIcon',
            'name' => 'partner.accounting.cash-flow',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.equity_changes',
            'group' => 'partner.accounting',
            'submenu' => 'reports',
            'link' => '/admin/partner/accounting/equity-changes',
            'icon' => 'ArrowTrendingUpIcon',
            'name' => 'partner.accounting.equity-changes',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.fixed_assets',
            'group' => 'partner.accounting',
            'submenu' => 'reports',
            'link' => '/admin/partner/accounting/fixed-assets',
            'icon' => 'CubeIcon',
            'name' => 'partner.accounting.fixed-assets',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.inventory',
            'group' => 'partner.accounting',
            'submenu' => 'reports',
            'link' => '/admin/partner/accounting/inventory',
            'icon' => 'ArchiveBoxIcon',
            'name' => 'partner.accounting.inventory',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.ios_statement',
            'group' => 'partner.accounting',
            'submenu' => 'reports',
            'link' => '/admin/partner/accounting/ios-statement',
            'icon' => 'DocumentCheckIcon',
            'name' => 'partner.accounting.ios-statement',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        // ── Tax & Closing (Даноци и затворање) ──
        [
            'title' => 'partner.accounting.vat_books',
            'group' => 'partner.accounting',
            'submenu' => 'compliance',
            'link' => '/admin/partner/accounting/vat-books',
            'icon' => 'BookOpenIcon',
            'name' => 'partner.accounting.vat-books',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.trade_book',
            'group' => 'partner.accounting',
            'submenu' => 'compliance',
            'link' => '/admin/partner/accounting/trade-book',
            'icon' => 'BookOpenIcon',
            'name' => 'partner.accounting.trade-book',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => '',
        ],
        [
            'title' => 'partner.accounting.vat_returns',
            'group' => 'partner.accounting',
            'submenu' => 'compliance',
            'link' => '/admin/partner/accounting/vat-returns',
            'icon' => 'DocumentArrowUpIcon',
            'name' => 'partner.accounting.vat-returns',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.ujp_forms',
            'group' => 'partner.accounting',
            'submenu' => 'compliance',
            'link' => '/admin/partner/accounting/ujp-forms',
            'icon' => 'DocumentTextIcon',
            'name' => 'partner.accounting.ujp-forms',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.payroll_reports',
            'group' => 'partner.accounting',
            'submenu' => 'compliance',
            'link' => '/admin/partner/accounting/payroll-reports',
            'icon' => 'UserGroupIcon',
            'name' => 'partner.accounting.payroll-reports',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'payroll',
        ],
        [
            'title' => 'partner.accounting.activity_log',
            'group' => 'partner.accounting',
            'submenu' => 'compliance',
            'link' => '/admin/partner/accounting/activity-log',
            'icon' => 'ClipboardDocumentListIcon',
            'name' => 'partner.accounting.activity-log',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => '',
        ],
        [
            'title' => 'partner.accounting.period_lock',
            'group' => 'partner.accounting',
            'submenu' => 'compliance',
            'link' => '/admin/partner/accounting/period-lock',
            'icon' => 'LockClosedIcon',
            'name' => 'partner.accounting.period-lock',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.year_end_closing',
            'group' => 'partner.accounting',
            'submenu' => 'compliance',
            'link' => '/admin/partner/accounting/year-end',
            'icon' => 'FlagIcon',
            'name' => 'partner.accounting.year-end',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        // Cost Centers → moved to Operations Hub (accessible by partners via company menu)
        // CLAUDE-CHECKPOINT
        // ── Ledgers (new features) ──
        [
            'title' => 'partner.accounting.compensations',
            'group' => 'partner.accounting',
            'submenu' => 'ledgers',
            'link' => '/admin/partner/accounting/compensations',
            'icon' => 'ArrowsRightLeftIcon',
            'name' => 'partner.accounting.compensations',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.payment_orders',
            'group' => 'partner.accounting',
            'submenu' => 'ledgers',
            'link' => '/admin/partner/accounting/payment-orders',
            'icon' => 'BanknotesIcon',
            'name' => 'partner.accounting.payment-orders',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.purchase_orders',
            'group' => 'partner.accounting',
            'submenu' => 'ledgers',
            'link' => '/admin/partner/accounting/purchase-orders',
            'icon' => 'ShoppingCartIcon',
            'name' => 'partner.accounting.purchase-orders',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        // ── Reports (new features) ──
        [
            'title' => 'partner.accounting.budgets',
            'group' => 'partner.accounting',
            'submenu' => 'reports',
            'link' => '/admin/partner/accounting/budgets',
            'icon' => 'CalculatorIcon',
            'name' => 'partner.accounting.budgets',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.bi_dashboard',
            'group' => 'partner.accounting',
            'submenu' => 'reports',
            'link' => '/admin/partner/accounting/bi-dashboard',
            'icon' => 'PresentationChartLineIcon',
            'name' => 'partner.accounting.bi-dashboard',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.custom_reports',
            'group' => 'partner.accounting',
            'submenu' => 'reports',
            'link' => '/admin/partner/accounting/custom-reports',
            'icon' => 'DocumentChartBarIcon',
            'name' => 'partner.accounting.custom-reports',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.travel_orders',
            'group' => 'partner.accounting',
            'submenu' => 'reports',
            'link' => '/admin/partner/accounting/travel-orders',
            'icon' => 'TruckIcon',
            'name' => 'partner.accounting.travel-orders',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.consolidation',
            'group' => 'partner.accounting',
            'submenu' => 'reports',
            'link' => '/admin/partner/accounting/consolidation',
            'icon' => 'BuildingOffice2Icon',
            'name' => 'partner.accounting.consolidation',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        // ── Compliance (new features) ──
        [
            'title' => 'partner.accounting.interest',
            'group' => 'partner.accounting',
            'submenu' => 'compliance',
            'link' => '/admin/partner/accounting/interest',
            'icon' => 'ReceiptPercentIcon',
            'name' => 'partner.accounting.interest',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.collections',
            'group' => 'partner.accounting',
            'submenu' => 'compliance',
            'link' => '/admin/partner/accounting/collections',
            'icon' => 'BellAlertIcon',
            'name' => 'partner.accounting.collections',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        [
            'title' => 'partner.accounting.batch_operations',
            'group' => 'partner.accounting',
            'submenu' => 'compliance',
            'link' => '/admin/partner/accounting/batch-operations',
            'icon' => 'CpuChipIcon',
            'name' => 'partner.accounting.batch-operations',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
            'feature_flag' => 'accounting_backbone',
        ],
        // ── Back to Dashboard ──
        [
            'title' => 'partner.accounting.partner_dashboard',
            'group' => 'partner.accounting',
            'link' => '/admin/console',
            'icon' => 'ArrowUturnLeftIcon',
            'name' => 'partner.accounting.partner-dashboard',
            'owner_only' => false,
            'ability' => '',
            'model' => '',
        ],
    ],

    /*
    * List of customer portal menu
    */
    'customer_menu' => [
        [
            'title' => 'navigation.dashboard',
            'link' => '/customer/dashboard',
            'icon' => '',
            'name' => '',
            'ability' => '',
            'owner_only' => false,
            'group' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.invoices',
            'link' => '/customer/invoices',
            'icon' => '',
            'name' => '',
            'ability' => '',
            'owner_only' => false,
            'group' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.estimates',
            'link' => '/customer/estimates',
            'icon' => '',
            'name' => '',
            'owner_only' => false,
            'ability' => '',
            'group' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.payments',
            'link' => '/customer/payments',
            'icon' => '',
            'name' => '',
            'owner_only' => false,
            'ability' => '',
            'group' => '',
            'model' => '',
        ],
        [
            'title' => 'navigation.settings',
            'link' => '/customer/settings',
            'icon' => '',
            'name' => '',
            'owner_only' => false,
            'ability' => '',
            'group' => '',
            'model' => '',
        ],
    ],

    /*
    * List of recurring invoice status
    */
    'recurring_invoice_status' => [
        'create_status' => [
            ['key' => 'settings.preferences.active', 'value' => 'ACTIVE'],
            ['key' => 'settings.preferences.on_hold', 'value' => 'ON_HOLD'],
        ],
        'update_status' => [
            ['key' => 'settings.preferences.active', 'value' => 'ACTIVE'],
            ['key' => 'settings.preferences.on_hold', 'value' => 'ON_HOLD'],
            ['key' => 'settings.preferences.completed', 'value' => 'COMPLETED'],
        ],
    ],

    /*
    * List of exchange rate provider (currency converter server's)
    */
    'currency_converter_servers' => [
        ['key' => 'settings.preferences.premium', 'value' => 'PREMIUM'],
        ['key' => 'settings.preferences.prepaid', 'value' => 'PREPAID'],
        ['key' => 'settings.preferences.free', 'value' => 'FREE'],
        ['key' => 'settings.preferences.dedicated', 'value' => 'DEDICATED'],
    ],

    /*
    * List of exchange rate drivers
    */
    'exchange_rate_drivers' => [
        ['key' => 'settings.exchange_rate.currency_converter', 'value' => 'currency_converter'],
        ['key' => 'settings.exchange_rate.currency_freak', 'value' => 'currency_freak'],
        ['key' => 'settings.exchange_rate.currency_layer', 'value' => 'currency_layer'],
        ['key' => 'settings.exchange_rate.open_exchange_rate', 'value' => 'open_exchange_rate'],
    ],

    /*
    * List of Custom field supported models
    */
    'custom_field_models' => [
        'Customer',
        'Estimate',
        'Invoice',
        'Payment',
        'Expense',
    ],
];

// LLM-CHECKPOINT

// LLM-CHECKPOINT
// CLAUDE-CHECKPOINT PAF-10: Added partner accounting navigation menu
// CLAUDE-CHECKPOINT: Removed certificates menu entry - no UI component available
// CLAUDE-CHECKPOINT: Set owner_only=true for Tax Types, Payment Modes, Custom Fields, Expense Category, Exchange Rate Provider
