<?php
/**
 * Simple PHP script to create a test PDF for INV-01 barcode/QR testing
 * Uses basic PDF creation without external dependencies
 */

// Simple PDF creation function
function createTestPDF($filename) {
    $pdf_content = "%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
/Resources <<
  /Font <<
    /F1 5 0 R
  >>
>>
>>
endobj

4 0 obj
<<
/Length 500
>>
stream
BT
/F1 16 Tf
50 750 Td
(Sample Invoice - Test Document) Tj
0 -30 Td
/F1 12 Tf
(Invoice Number: INV-2025-001) Tj
0 -20 Td
(Date: 2025-01-15) Tj
0 -20 Td
(Amount: 1,200.00 MKD) Tj
0 -20 Td
(Customer: Test Customer Ltd.) Tj
0 -50 Td
(QR Code Placeholder: [INV-2025-001|1200.00|MKD|2025-01-15]) Tj
0 -30 Td
(Barcode Placeholder: INV2025001) Tj
0 -50 Td
/F1 10 Tf
(This is a test document for QR code and barcode recognition testing.) Tj
0 -15 Td
(Generated for InvoiceShelf INV-01 development.) Tj
0 -15 Td
(Note: Real QR codes and barcodes will be generated by picqer packages.) Tj
ET
endstream
endobj

5 0 obj
<<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica
>>
endobj

xref
0 6
0000000000 65535 f 
0000000015 00000 n 
0000000068 00000 n 
0000000125 00000 n 
0000000268 00000 n 
0000000824 00000 n 
trailer
<<
/Size 6
/Root 1 0 R
>>
startxref
891
%%EOF";

    file_put_contents($filename, $pdf_content);
    return true;
}

// Create the test PDF
$filename = __DIR__ . '/sample.pdf';

if (createTestPDF($filename)) {
    echo "Created test PDF: $filename\n";
    echo "File size: " . filesize($filename) . " bytes\n";
} else {
    echo "Failed to create test PDF\n";
    exit(1);
}
?>